
version: 2

sources:
  - name: safetravel
    tables:
      - name: earthquake
      - name: world_development_indicators
      - name: world_development_over
      - name : world_development_short
      - name : world_development_scores
      - name: emergency
      - name: Health_source

